src/constants/labels.json

LUN-191: Rename module "Modul" to "Beruf"

---

release-notes/unreleased/LUN-214-Missing-Connection-Adding-Discipline.yml
src/hooks/__tests__/useLoadFromEndpoint.spec.ts
src/routes/AddCustomDisciplineScreen.tsx
src/services/axios.ts
src/services/helpers.ts

Please test this issue on IOS!
Probably its not the best way to fix it on FE. We can discuss better ways
Maybe we should just check the Apache Logs.
Feel free to discuss

LUN-214: Missing connection when adding discipline

---

ios/Lunes/LaunchScreen.storyboard

Had to convert the rgb values to fit for ios splashscreen using srgb.
Easiest way is to adjust the "RGB Slider" settings to srgb profile
Further Info:
https://github.com/expo/expo/issues/826#issuecomment-494283319

LUN-115: Adjust rgb values by using generic rgb profile values

---

release-notes/unreleased/LUN-235-fix-back-navigation-in-resultscreen.yml
src/navigation/Navigator.tsx

I think just use the goBack functionality should do the trick. Don't know why we need here an explicit screen.
I hope i haven't overseen anything

LUN-235: Fix back navigation in resultscreen

---

src/components/Button.tsx
src/components/ConfirmationModal.tsx
src/components/CustomDisciplineItem.tsx
src/components/DisciplineItem.tsx
src/components/ExerciseHeader.tsx
src/components/Title.tsx
src/components/text/Content.tsx
src/components/text/Heading.tsx
src/components/text/ItemTitle.tsx
src/components/text/Subheading.tsx
src/routes/DisciplineSelectionScreen.tsx
src/routes/ExercisesScreens.tsx
src/routes/HomeScreen.tsx
src/routes/InitialSummaryScreen.tsx
src/routes/ResultsOverviewScreen.tsx
src/routes/add-custom-discipline/AddCustomDisciplineScreen.tsx
src/routes/add-custom-discipline/components/NotAuthorisedView.tsx
src/routes/choice-exercises/components/SingleChoiceListItem.tsx
src/routes/vocabulary-list/components/VocabularyListItem.tsx
src/routes/write-exercise/components/MissingArticlePopover.tsx

I created text component with according to the following schema:
`<TextType><Color><FontWeight>`
Example:
`ContentSecondaryLight`
If there are any better suggestions, please let me know

LUN-247: Create reusable styled components for texts

---

release-notes/unreleased/LUN-272-incorrect-names-for-additional-areas.yml
src/components/CustomDisciplineItem.tsx
src/components/ListItem.tsx
src/components/ServerResponseHandler.tsx
src/hooks/__tests__/useLoadFromEndpoint.spec.ts
src/routes/DisciplineSelectionScreen.tsx
src/services/axios.ts

I fixed several things here:
1) Wrong names of multiple custom disciplines: axios-cache did handle them the same way as they only differ in the Auth-header.
2) Jumping of custom disciplines, because container while loading has different size/margins
3) Error message above Title in a module, when loading fails which looks bad, see here https://issues.tuerantuer.org/browse/LUN-271
api-key for testing:
rXTIfCwz.eOYXwwn486fR5PlKFW9KagLtIzwwBCrE
qYA.YYyZben

LUN-272: Incorrect names for additional areas

---

release-notes/unreleased/LUN-289-show-empty-custom-disciplines.yml
src/components/DisciplineListItem.tsx

LUN-289: Show empty custom disciplines

---

ios/Lunes/Info.plist
src/services/url.ts

Both fixes are only necessary for emulators to avoid errors. On real devices everything works as expected.
`tel` & `mailto` can only be tested on real ios devices. Just added handling for not supported devices like emulators
Impressum-> Click on mailaddress

LUN-282: Error unable to open url mailto

---

src/hooks/useLoadAsync.ts
src/navigation/NavigationTypes.ts
src/navigation/Navigator.tsx
src/routes/DisciplineSelectionScreen.tsx
src/routes/ExercisesScreen.tsx

Choose a discipline and check if the exercise screen uses correct header for navigation and list

LUN-318: Exercises screen shows wrong list title

---

src/components/SingleChoiceListItem.tsx
src/components/WordItem.tsx
src/routes/choice-exercises/components/SingleChoice.tsx
src/routes/choice-exercises/components/SingleChoiceExercise.tsx
src/routes/vocabulary-list/components/VocabularyListModal.tsx

I decided to keep this refactoring quite small because we have to keep the color logic in the component because its depending on state. I could have made a `SingleChoiceItemWrapper` but it's not worth in my opinion. To use the `ListItem` would mean to but a lot of additional logic inside which would make the component itself too complicated. Feel free for discussion if there are better proposals for refactoring

LUN-138: Resusable-SingleChoiceListItem

---

src/constants/data.ts
src/navigation/Navigator.tsx
src/routes/vocabulary-list/VocabularyListScreen.tsx
src/routes/vocabulary-list/__tests__/VocabularyListScreen.spec.tsx
src/services/__tests__/helpers.spec.tsx
src/services/helpers.ts

LUN-342: Save progress of vocabulary list

---

src/constants/labels.json

LUN-375: Swap 'gemeistert' for 'gemacht' in excercise feedback

---

tools/git-version.ts
tools/github-release.ts
tools/jira-release.ts
tools/manage-metadata.ts
tools/move-release-notes.ts

Seems like it always have to first be command, then options and only then the action. Otherwise the options are just lost. Only tested commands where this was the case last time :/

LUN-393: Fix failing commands

---

tools/constants.ts

As our Lunes update in Apple store was rejected, because the default notes were not specific enough, I changed them (to the Integreat default)

LUN-xx: Adjust default notes

---

assets/images/add-icon-white.svg
assets/images/index.ts
src/components/Button.tsx
src/components/ListEmpty.tsx
src/components/SearchBar.tsx
src/constants/data.ts
src/constants/labels.json
src/hooks/useReadUserVocabulary.ts
src/navigation/BottomTabNavigator.tsx
src/navigation/DictionaryStackNavigator.tsx
src/navigation/NavigationTypes.ts
src/navigation/UserVocabularyStackNavigator.tsx
src/routes/UserVocabularyOverviewScreen.tsx
src/routes/VocabularyDetailScreen.tsx
src/routes/__tests__/UserVocabularyOverviewScreen.spec.tsx
src/routes/dictionary/DictionaryScreen.tsx
src/routes/dictionary/__tests__/DictionaryScreen.spec.tsx
src/routes/user-vocabulary-list/UserVocabularyListScreen.tsx
src/routes/user-vocabulary-list/__tests__/UserVocabularyListScreen.spec.tsx
src/routes/user-vocabulary-list/components/ListEmptyContent.tsx
src/services/AsyncStorage.ts
src/services/__tests__/AsyncStorage.spec.ts
src/services/helpers.ts

To test this, you need to add some data to AsyncStorage:
```
const a = new DocumentBuild(4).build()
AsyncStorage.addUserDocument({...a[0]})
....
```
and so on..

LUN-395: User created vocabulary list screen

---

ios/Podfile

Only testblable with apple m1
1. run `yarn install` `/ios/pod install` and build project on simulator

LUN-445: Fix pods m1

---

release-notes/unreleased/LUN-447-fix-overlap.yml
src/routes/choice-exercises/components/SingleChoiceExercise.tsx

This pull request belongs to the issue https://issues.tuerantuer.org/browse/LUN-447 .
Screenshot from a Nexus S:

LUN-447: Fix overlap on choice exercises

---

src/components/__tests__/NotAuthorisedView.spec.tsx

LUN-450: write tests for NotAuthorizedView

---

Gemfile.lock
android/Gemfile.lock
ios/Gemfile.lock
release-notes/LUN-472-security-updates.yml
tools/yarn.lock
yarn.lock

This pull request belongs to https://issues.tuerantuer.org/browse/LUN-472. It fixes the vulnerability alerts that Dependabot can't fix by itself.

LUN-472: Dependabot vulnerability alerts

---

ios/Podfile.lock
package.json
yarn.lock

This pull request fixes an issue where some XCode versions throw the error "'value' is unavailable: introduced in iOS 12.0" when building. More here: https://github.com/facebook/react-native/issues/34106

LUN-XXX: Fix for XCode

---

ios/Gemfile.lock
src/services/__tests__/axios.spec.ts
src/services/__tests__/url.spec.ts
src/services/axios.ts
src/services/url.ts

Remove a workaround that adds a trailing slash to each api request.
- remove workaround
N/A
Fixes: #669
---

699: remove trailing slash workaround

---

.circleci/config.yml
.circleci/src/jobs/build_ios.yml

Switch from old deprecated x86 to m1 resource class because tests will fail in the end of the year
Switch resource classes for ios builds if deprecated resource are in use
resolves #990

990: Update macos resource classes

---

ios/fastlane/Appfile

Changed the app store mail to be the same as for all other apps, as this makes the regular updates of the certificates easier and we are more likely not to look us out from our shared accounts, as they can be quite a pain, because of how the 2FA works.

Unify apple account used for app signing

---

.circleci/config.yml
.circleci/src/commands/notify.yml
CODEOWNERS

Remove Sarah and Max from Notifications and codeowners

---

.circleci/config.yml
.circleci/src/jobs/build_android.yml
.circleci/src/jobs/deliver_android.yml
.circleci/src/jobs/deliver_browser_stack.yml
.circleci/src/jobs/promote_android.yml

Since android images get EOL in september, we have to upgrade them
- upgrade to cimg/android:2024.01.1-node
Fixes: #1009
---

1009: Upgrade android images

---

.circleci/config.yml
.circleci/src/jobs/build_ios.yml
.circleci/src/jobs/deliver_ios.yml
.circleci/src/jobs/promote_ios.yml
ios/Podfile

Since we won't be able to publish ios apps after 29th of April, with XCode 14, we have to upgrade to xcode 15
- upgrade to xcode15
Fixes: #1017
---

1017: Upgrade xcode 15

---

.circleci/config.yml
.circleci/src/commands/restore_ruby_cache.yml

With the new android images it seems like the permissions to folders changed and there are issues with ruby gems.
- added `sudo` to bundle install
Here you can check that android builds successfully
https://app.circleci.com/pipelines/github/digitalfabrik/lunes-app/3514/workflows/7a8e9e73-13c7-4e38-9924-5e50ebb27beb/jobs/11718
ios failed due to  #1017  wasn't merged
https://github.com/rubygems/rubygems/issues/6290

1009: Fix ruby gems

---

src/navigation/HomeStackNavigator.tsx
src/navigation/Navigator.tsx

This pr fixes a bug where the sidebar stayed open when clicking on "Lernbereiche verwalten" and then going back.
Should I include a release not for this small bugfix?
- Move the `ManageSelectionScreen` from the root navigator to the `HomeStackNavigator`, so that react pops the menu, instead of putting the screen on top of it
- Hopefully none :D
Fixes: #1046
---

1046: Close sidebar menu on navigation back

---

src/components/ExerciseHeader.tsx

After upgrading react native to v0.74, the react-native-paper was also updated which resulted in the `loss precision error`. The `progress` prop of` ProgressBar `component caused this issue. The workaround is mentioned [here](https://github.com/facebook/react-native/issues/47635#issuecomment-2507431266)
- Change the `progress` prop to `animatedValue`
- should be none :)
Fixes: #1051 
---

1051: Fix loss of precision error in vocabulary list

---

src/components/Button.tsx
src/constants/labels.json
src/routes/repetition/RepetitionScreen.tsx
src/routes/repetition/__tests__/RepetitionScreen.spec.tsx
src/services/helpers.ts

This pr addresses #1042 , which solves two problems:
- Add a text to the long term repetition info modal
- Fix the pluralization of the `wordsToRepeat` label
- (Not part of the original issue) Disable the repetition button if there are no words to repeat
should be none
Fixes: #1042 
---

1042: Add text to long term excercise

---

src/navigation/BottomTabNavigator.tsx

This pr hides the repetition badge number if it is zero. This fixes the non-duplicate part of issue #995.
- Hide number if zero
none
Fixes: #995
---

Hide the repetition badge number if it is zero

---

src/navigation/UserVocabularyStackNavigator.tsx
src/routes/VocabularyDetailScreen.tsx

Adds a button to the vocabulary details screen that navigates to the vocabulary process screen.
This button will only be visible in the "my words" tab, but not in the vocabulary details screens from the favorites tab or the search tab.
- Add `EditableVocabularyDetailsScreen` component
- If editable, show a button to navigation to the process screen in the navigation bar
/
Fixes: #917 
---

917: Add edit button to vocabulary detail screen

---

src/constants/labels.json

This pr fixes the ellipsis that is shown in the bottom tab navigator on devices with small screens.
- Rename "Wiederholen" to "Vertiefen"
- Rename "Meine Wörter" to "Sammlung"
* This is still cut off on a small iphone
Fixes: #1041
---

Fix bottom tab texts being cut off

---

android/app/src/main/AndroidManifest.xml

It should not be required anymore, because android now has the media picker. This pr will ideally fix the release.
- Remove the permission from android manifest
- Ideally none
Fixes: /
---

Remove android `READ_MEDIA_IMAGES` permission

---

ios/Lunes/Info.plist

According to the documentation, `armv64` is not an allowed value here: https://developer.apple.com/documentation/bundleresources/information-property-list/uirequireddevicecapabilities This also matches the value we have in the integreat app
- Change to value to `arm64`
- maybe app upload works now? :)
Fixes: /
---

IOS: Fix value for `UIRequiredDeviceCapabilities`

---

docs/cicd.md

It is possible to trigger a workflow using the circleCI user interface, instead of sending a POST request. Since this is a bit simpler, mention it in the docs
- Mention the possibility of using ui in the docs
/
Fixes: /
---

Add note about circle ci ui for creating a new release

---

src/routes/write-exercise/__tests__/WriteExerciseScreen.spec.tsx
src/routes/write-exercise/services/StandardWriteExerciseService.ts

Add write exercise words to long term exercise after the write exercise has been finished
- Add the words from the standardWriteExerciseService when finish is called
-
Fixes: #1038 
---

1038: add words to long term exercise

---

src/components/FavoriteButton.tsx
src/services/AsyncStorage.ts
src/services/__tests__/AsyncStorage.spec.ts
src/services/helpers.ts

Also add words to the long term exercise when they are marked as favorites.
As per issue, they will not be removed from the long term exercise when they are removed as favorites.
- Add the word to the repetition service in AsyncStorage
- I am not sure if that is the best place to do it, do the reviewers have any opinions on that?
- Bug #1040 now also occurs when a favorite is added, which raises its priority
Fixes: #1039 
---

1039: add favorites to long term excercise

---

src/constants/labels.json
src/navigation/BottomTabNavigator.tsx
src/navigation/NavigationTypes.ts
src/navigation/UserVocabularyStackNavigator.tsx
src/routes/UserVocabularyOverviewScreen.tsx
src/routes/VocabularyDetailScreen.tsx
src/routes/process-user-vocabulary/UserVocabularyProcessScreen.tsx
src/routes/process-user-vocabulary/__tests__/UserVocabularyProcessScreen.spec.tsx
src/routes/user-vocabulary-discipline-selection/UserVocabularyDisciplineSelectionScreen.tsx
src/routes/user-vocabulary-discipline-selection/__tests__/UserVocabularyDisciplineSelectionScreen.spec.tsx
src/routes/user-vocabulary-discipline-selection/splitVocabularyToDiscipline.ts
src/routes/user-vocabulary-list/UserVocabularyListScreen.tsx

In #1062 I forgot to update the labels in the user vocabulary screens, but they did not make too much sense anymore.
- Change the labels from "Sammlung" to be more specific and user more generic back labels
Fixes: #1067
---

Fix wrong labels in user vocabulary

---

release-notes/unreleased/906-cleanup-long-term-exercise.yml
src/navigation/BottomTabNavigator.tsx
src/routes/exercise-finished/ExerciseFinishedScreen.tsx
src/routes/exercise-finished/__tests__/ExerciseFinishedScreen.spec.tsx

This pr makes the long term exercise public. Not all planned features for it are implemented yet, but we decided to publish it rather sooner than later.
- Remove `isDevModeEnabled` checks
- Enable disabled test
- Remove unused icon function
- Long term exercise should now be enabled for all users
Long term exercise should be accessible to all users and words and favorites should get added to it
Fixes: #906 
---

Cleanup long term exercise

---

package.json
release-notes/unreleased/1072.yml
yarn.lock

Our popover library does not support reacts new architecture on older versions (https://github.com/SteffeyDev/react-native-popover-view/releases/tag/v6.0.0)
- Update the popover library
Just need to test that the missing article popover shows up.
I also wanted to write a test for that, but for some reason the popover does not show up at all in the dom 🤷 
Fixes: #1072 
---

Fix app freeze when entering a word without article

---

src/components/VocabularyDetail.tsx
src/navigation/FavoritesStackNavigator.tsx

The favorite view had the same problem as the user vocabulary view (Fixed in commit 895bbec853b3433202daffaf01ee4268d4ed77da)
This pr applies the same fix to the favorites stack navigator.
- In the favorite stack navigator, explicitly set the header height to 0, so that the content does not have unnecessary padding applied to it.
- Should not change anything on android devices
Fixes: #1079 
---

1079: Fix word cut off on favorite view on IOS

---

assets/images/volume-up-circle-icon.svg
release-notes/unreleased/1083-speaker-button-not-greyed-out.yml

Turns out we were already using the correct colors for the icon, but they were fully covered by the background of the icon…
This pr simplifies the svg icon by removing the background from it.
- Remove background from assets/images/volume-up-circle-icon.svg
- The colors that were already being applied to the background should now show up
Fixes: #1083 
---

Fix volume icon not greyed out correctly

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/task.md
.github/ISSUE_TEMPLATE/user-story.md

We have updated all open issues with labels `task`, `bug`, or `Story` to use types instead. Now the issue templates should be updated too.
The changes are untested, but I am hoping that this documentation is accurate: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#top-level-syntax
- Switch from labels to types in the issue templates
Fixes: #1090 
---

Update issue templates to use issue types instead of labels

---

src/constants/labels.json
src/routes/settings/SettingsScreen.tsx
src/routes/settings/components/DebugModal.tsx
src/routes/settings/components/__tests__/DebugModal.spec.tsx

This pr contains two small improvements to the debug modal
- Add a setting to the debug modal to clear the selected professions. This makes it a bit easier to test the welcome screen on ios
- Add a debug settings button to the main settings if dev mode is already enabled. This avoids having to type the pass phrase every time
- There should not be any side effects if dev mode is disabled
---

Small debug modal improvements

---

ios/Lunes/Info.plist

- We don't need the location permission for the lunes app, and the android variant does also not declare it
- Not sure why it was here in the first place though
- Remove the permission from the ios manifest
- should be none
App should still work
Fixes: #1082
---

Remove unused ios permission

---

release-notes/unreleased/1089-tts-does-not-work-on-ios.yml
src/components/AudioPlayer.tsx

Tts not working on ios was a bug actually. It did not work because the tts engine returns `true` instead of `'success'` for some reason. I think this fix to just remove the check should work, because this is how it is suggested in the repo: https://github.com/ak1394/react-native-tts?tab=readme-ov-file#waiting-for-initialization
- Remove the check for the status code after initialization. Errors should be reported in the `.catch(...)` part
I tested this on ios, android and an android without a tts engine, and everything seemed to work as expected
Fixes: #1089
---

Enable tts for ios

---

src/constants/labels.json
src/routes/exercise-finished/ExerciseFinishedScreen.tsx
src/routes/exercise-finished/__tests__/ExerciseFinishedScreen.spec.tsx

The previous label was not accurate because it only takes you back to the discipline overview if you started the exercise from there
- Rename the button
- none
Fixes: #946 
---

Rename `disciplineOverview` button to `back`

---

android/build.gradle
ios/Podfile.lock
package.json
src/navigation/BottomTabNavigator.tsx
yarn.lock

This is required by google, so that we can continue pushing updates
- Update the target sdk to 35
- Update `react-native-safe-area-context`
- Fix calculation of bottom tab bar height
- As a side effect of android sdk 35, edge to edge navigation is now enabled by default. To me everything looks fine (except the one small bug with the height calculation of the bottom tab bar height that I fixed), but worst case we could also disable it again
- Potentially other side effects of the new sdk, but I did not find any
Fixes: #1104
---

Update target sdk to 35

---

release-notes/unreleased/1088-move-words-to-long-term-memory-exercise-after-each-level.yml
src/constants/data.ts
src/routes/exercise-finished/ExerciseFinishedScreen.tsx
src/routes/exercise-finished/__tests__/ExerciseFinishedScreen.spec.tsx
src/routes/write-exercise/__tests__/WriteExerciseScreen.spec.tsx
src/routes/write-exercise/services/RepetitionWriteExerciseService.ts
src/routes/write-exercise/services/StandardWriteExerciseService.ts
src/services/RepetitionService.ts
src/services/__tests__/RepetitionService.spec.ts
src/services/__tests__/storageUtils.spec.ts
src/services/__tests__/url.spec.ts
src/services/storageUtils.ts

This pr changes the behavior of when new words are added to the long term memory exercise. Before, this only happened when every level was completed and now it will happen after the second level (every level except the word list)
- Move the functionality to add words to the long term memory exercise to the `saveExerciseProgress` function
- Adjust tests
- Adjust when the repetition reminder is shown
Fixes: #1088
---

Move words to long term memory exercise after first level

---

src/components/RouteWrapper.tsx
src/routes/OverlayMenuScreen.tsx
src/routes/ProfessionSelectionScreen.tsx
src/routes/VocabularyListScreen.tsx
src/routes/home/HomeScreen.tsx
src/routes/scope-selection/ScopeSelectionScreen.tsx

With android 15 in some parts, `SafeArea` will get handled differently and we need to define some paddings for particular screens to avoid overlapping
- add `shouldSetBottomInset` and `shouldSetTopInset` to `RouteWrapper`
- use the inset on routes if needed
- likely none
- start application with Android Bottom Navigation instead of gesture navigation
- Check `HomeScreen`, `Scope`, `ProfessionSelection` and `VocabularyList` for content overlapping or other glitches
- Test with android and ios
Fixes: #1106
---

1106: Android content overlay

---

android/app/src/main/AndroidManifest.xml

This permission was used before for `react-native-image-crop-picker`, but not anymore (see comments of #1059 )
- Remove the permission
Test creating new vocabulary and adding images and sound to it. I tested it on emulated android api 35 and api 26
Fixes: #1059 
---

Remove unused `READ_EXTERNAL_STORAGE` permission

---

.circleci/config.yml
.circleci/src/jobs/build_android.yml
android/fastlane/Fastfile
release-notes/unreleased/1115-reduce-app-size.yml

This should reduce the app size.
We keep compiling apks as well, since they are more useful for debugging and as release assets.
Related: https://github.com/digitalfabrik/integreat-app/pull/2977/
The current compressed download size is 44.3MB according to google play, lets see if that improves at the next beta release with this pr (Google estimates -23MB if we use aabs)
- Generate an app bundle as well
- Upload the app bundle to google play, instead of the apk
- Keep the apks as release assets for github releases and mattermost notifications
- Probably slower ci times
We can only really test this when creating the next beta release
Fixes: #1115 
---

Upload aab to google play instead of apk

---

release-notes/unreleased/1149-remove-suggest-alternative-word-button.yml
src/routes/vocabulary-detail-exercise/components/AlternativeWordsSection.tsx
src/routes/vocabulary-detail-exercise/components/__tests__/AlternativeWords.spec.tsx

Alternative words can still be suggested via the context menu, but the button was too confusing for users.
- Don't show the button anymore in wordlists
- Completely hide the `AlternativeWordSection` if no alternatives exist
None
Test that wordlists still work
Fixes: #1149 
---

Remove suggest remove alternative word button
