assets/images/index.ts, src/interfaces/exercise.ts, src/screens/ResultScreen.tsx, src/screens/VocabularyOverviewExerciseScreen.tsx, src/screens/VocabularyTrainerExerciseScreen.tsx
=> LUN-53: Fix images

.eslintrc.js, src/components/Header.tsx, src/components/MenuItem.tsx, src/constants/data.ts, src/constants/endpoints.ts, src/navigation/NavigationTypes.ts, src/navigation/Navigator.tsx, src/screens/ExercisesScreens.tsx, src/screens/InitialSummaryScreen.tsx, src/screens/ProfessionScreen.tsx, src/screens/ProfessionSubcategoryScreen.tsx, src/screens/ResultScreen.tsx, src/screens/ResultsOverviewScreen.tsx, src/screens/VocabularyOverviewExerciseScreen.tsx, src/screens/VocabularyTrainerExerciseScreen.tsx, src/utils/__tests__/helper.spec.tsx, src/utils/helpers.ts
=> LUN-5: Type react navigation

ios/Lunes.xcodeproj/project.pbxproj, ios/Lunes/Info.plist
=> LUN-xx: Adjustments for signing app locally

src/components/Actions.tsx, src/components/AnswerSection.tsx, src/components/FeedbackSection.tsx, src/components/Modal.tsx, src/components/PopoverContent.tsx, src/constants/data.ts, src/navigation/Navigator.tsx, src/screens/ExercisesScreens.tsx, src/screens/InitialSummaryScreen.tsx, src/screens/ProfessionScreen.tsx, src/screens/ProfessionSubcategoryScreen.tsx, src/screens/ResultScreen.tsx, src/screens/ResultsOverviewScreen.tsx, src/screens/VocabularyOverviewExerciseScreen.tsx, src/screens/VocabularyTrainerExerciseScreen.tsx
=> LUN-46: Translate labels

src/components/AnswerSection.tsx, src/constants/data.ts, src/screens/ExercisesScreens.tsx, src/screens/ResultsOverviewScreen.tsx, src/utils/AsyncStorage.ts
=> LUN-66: Fix Summary Screen

src/constants/data.ts, src/screens/ExercisesScreens.tsx, src/screens/ProfessionScreen.tsx, src/screens/ProfessionSubcategoryScreen.tsx
=> LUN-67: Remove empty elements

src/components/SingleChoice.tsx, src/components/SingleChoiceListItem.tsx, src/constants/data.ts, src/screens/ExercisesScreens.tsx, src/screens/LearnArticlesExerciseScreen.tsx, src/screens/SingleChoiceExerciseScreen.tsx
=> LUN-40: Logic of single choice exercise

src/components/AnswerSection.tsx, src/components/FeedbackSection.tsx
=> LUN-82: show correct if give up

src/components/FeedbackSection.tsx
Undid the changes, as they break the app.
=> LUN-82: fix

src/screens/ExercisesScreens.tsx
=> LUN-60: fix navigation multiple click bug

src/components/AnswerSection.tsx, src/components/VocabularyListItem.tsx, src/constants/data.ts, src/navigation/NavigationTypes.ts, src/navigation/Navigator.tsx, src/screens/InitialSummaryScreen.tsx, src/screens/ProfessionScreen.tsx, src/screens/ResultScreen.tsx, src/screens/ResultsOverviewScreen.tsx, src/screens/VocabularyListScreen.tsx, src/screens/WriteExerciseScreen.tsx, src/screens/choice-exercises/ArticleChoiceExerciseScreen.tsx, src/screens/choice-exercises/WordChoiceExerciseScreen.tsx
=> LUN-83: Rename Exercises

src/screens/ResultScreen.tsx, src/screens/choice-exercises/components/SingleChoiceExercise.tsx
=> LUN-99: Fix result screen bugs

src/screens/choice-exercises/components/SingleChoiceExercise.tsx
=> LUN-81: Check for alternative article

src/components/AnswerSection.tsx, src/components/AudioPlayer.tsx, src/components/FeedbackSection.tsx, src/components/VocabularyListItem.tsx, src/constants/data.ts, src/constants/endpoints.ts, src/hooks/useLoadDocuments.ts, src/screens/VocabularyListScreen.tsx, src/screens/WriteExerciseScreen.tsx, src/screens/choice-exercises/ArticleChoiceExerciseScreen.tsx, src/screens/choice-exercises/WordChoiceExerciseScreen.tsx, src/screens/choice-exercises/components/SingleChoiceExercise.tsx, src/screens/choice-exercises/components/SingleChoiceListItem.tsx, src/utils/axios.ts, src/utils/helpers.ts
=> LUN-100: Implement article cms changes

src/components/AnswerSection.tsx, src/screens/ResultScreen.tsx
=> LUN-xx: Fixes

src/constants/labels.json, src/screens/VocabularyListScreen.tsx, src/screens/WriteExerciseScreen.tsx
=> LUN-105: Fix word counter

CODEOWNERS
=> LUN-123: Update Codeowners

src/services/axios.ts
=> LUN-101: Use test cms for development

ios/Lunes.xcodeproj/project.pbxproj
=> LUN-6: Fix build

src/routes/vocabulary-list/components/VocabularyListItem.tsx
=> LUN-125: fixing the misplaced articles style on bigger screens

src/routes/write-exercise/components/AnswerSection.tsx
=> LUN-120 Almost correct word

src/routes/write-exercise/components/AnswerSection.tsx
=> LUN-49: Check entry by using enter / make screen scrollable

src/components/AudioPlayer.tsx
=> LUN-152: Only initialize tts or sound player

src/components/AudioPlayer.tsx
=> LUN-152: Fix audio files

release-notes/unreleased/LUN-148-multiline-wrap, src/components/MenuItem.tsx
=> LUN-148: Multiline wrap for menuItems

jest.setup.ts, release-notes/unreleased/LUN-69-alternative-tts.yml, src/components/AudioPlayer.tsx, src/components/__tests__/AudioPlayer.spec.tsx, src/routes/write-exercise/WriteExerciseScreen.tsx, src/routes/write-exercise/components/Actions.tsx, src/routes/write-exercise/components/WriteExercise.tsx, src/routes/write-exercise/components/__tests__/Actions.spec.tsx, src/routes/write-exercise/components/__tests__/WriteExercise.spec.tsx, src/services/helpers.ts
=> LUN 69: Play TTS for alternative solutions

src/components/ConfirmationModal.tsx, src/routes/InitialSummaryScreen.tsx, src/routes/write-exercise/WriteExerciseScreen.tsx, src/routes/write-exercise/components/WriteExercise.tsx, src/routes/write-exercise/components/__tests__/WriteExercise.spec.tsx, src/services/AsyncStorage.ts
=> LUN-141: Remove exercise results and sessions from async storage

src/components/MenuItem.tsx, src/routes/DisciplineSelectionScreen.tsx
=> LUN-220: Fix multiline style issue

src/routes/write-exercise/components/InteractionSection.tsx
=> LUN-199: Color of check input button wrong

release-notes/unreleased/LUN-227-fix-cut-off-header-text.yml, src/components/ExerciseHeader.tsx, src/components/NavigationHeaderLeft.ts, src/components/NavigationTitle.ts, src/navigation/Navigator.tsx
Fixed header text cut off.
**Test:**
Gastronomie, Lebensmittel -> Bäcker
Tested on android & ios (native and emulator)
=> LUN-227: Fix cut off header text

src/routes/add-custom-discipline/components/QRCodeReaderOverlay.tsx
=> LUN-232: Simplify permission handling

ios/Lunes/Info.plist, ios/Podfile, ios/Podfile.lock, package.json, src/constants/labels.json, src/routes/add-custom-discipline/__tests__/AddCustomDisciplineScreen.spec.tsx, src/routes/add-custom-discipline/components/QRCodeReaderOverlay.tsx, src/routes/add-custom-discipline/components/__tests__/QRCodeReaderOverlay.spec.tsx, yarn.lock
=> LUN-256: Added QR code scanner for ios

package.json, yarn.lock
=> LUN-261: Update axios-cache-interceptor

android/app/build.gradle, android/fastlane/Fastfile, android/settings.gradle, metro.config.ci.js, tsconfig.json
=> LUN-252-2: Fix failing build android step

src/routes/home/__tests__/HomeScreen.spec.tsx
=> LUN-180: Improve HomeScreen tests

ios/Lunes/Info.plist
=> LUN-268: Added required orientations for ipad

ios/fastlane/Fastfile
=> LUN-284: Fix ios promote

src/constants/labels.json
=> LUN-279: Add hint for qr code scanner

release-notes/unreleased/LUN-280-show-correct-solution-if-wrong.yml, release-notes/unreleased/LUN-289-show-empty-custom-disciplines.yml, src/routes/write-exercise/components/Feedback.tsx, src/routes/write-exercise/components/__tests__/Feedback.spec.tsx, src/routes/write-exercise/components/__tests__/WriteExercise.spec.tsx
Check how to Test in [LUN-280](https://issues.tuerantuer.org/browse/LUN-280)
=> LUN-280: Show correct solution if wrong

.circleci/config.yml, .circleci/src/jobs/notify_android.yml, .circleci/src/jobs/notify_ios.yml, .eslintignore, .eslintrc.js, tools/github-release.ts
=> LUN-286: Create GitHub releases

src/constants/data.ts, src/routes/ExercisesScreen.tsx, src/routes/ResultScreen.tsx, src/routes/exercise-finished/ExerciseFinishedScreen.tsx, src/routes/home/HomeScreen.tsx
=> LUN-326: Refactor next screen naming

src/constants/data.ts, src/constants/endpoints.ts, src/hooks/helpers.ts, src/hooks/useLoadDiscipline.ts, src/hooks/useLoadDisciplines.ts, src/hooks/useReadNextExercise.ts, src/hooks/useReadProgress.ts, src/hooks/useReadSelectedProfessions.ts, src/routes/ProfessionSelectionScreen.tsx, src/routes/__tests__/ProfessionSelectionScreen.spec.tsx, src/routes/home/HomeScreen.tsx, src/routes/home/__tests__/HomeScreen.spec.tsx, src/routes/home/components/CustomDiscipline.tsx, src/routes/home/components/DisciplineCard.tsx, src/routes/home/components/__tests__/DisciplineCard.spec.tsx, src/routes/manage-selections/ManageSelectionsScreen.tsx, src/routes/manage-selections/__tests__/ManageSelectionsScreen.spec.tsx, src/routes/scope-selection/__tests__/ScopeSelectionScreen.spec.tsx, src/services/AsyncStorage.ts, src/services/__tests__/AsyncStorage.spec.ts, src/services/__tests__/helpers.spec.tsx, src/services/helpers.ts
=> LUN-297: Refresh details of profession

release-notes/unreleased/LUN-314-exercise-height-should-be-100.yml, src/routes/vocabulary-list/components/VocabularyListModal.tsx
=> LUN-314: Exercise height should be 100 

src/components/ErrorMessage.tsx, src/constants/endpoints.ts, src/constants/labels.json, src/routes/home/HomeScreen.tsx, src/routes/home/components/Card.tsx, src/routes/home/components/CustomDiscipline.tsx, src/routes/home/components/DisciplineCard.tsx, src/routes/home/components/__tests__/CustomDiscipline.spec.tsx, src/routes/home/components/__tests__/DisciplineCard.spec.tsx, src/routes/manage-selections/ManageSelectionsScreen.tsx, src/routes/manage-selections/components/CustomDisciplineItem.tsx, src/routes/manage-selections/components/ProfessionItem.tsx, src/routes/manage-selections/components/SelectionItem.tsx, src/routes/manage-selections/components/__tests__/SeletionItem.spec.tsx
=> LUN-301: Add loading and error handling

src/components/FavoriteButton.tsx, src/components/__tests__/FavoriteButton.spec.tsx, src/constants/labels.json, src/routes/FavoritesScreen.tsx
=> LUN-132: Change FavoriteButton

release-notes/unreleased/LUN-292-add-switch-for-cms.yml, src/constants/labels.json, src/routes/settings/components/DebugModal.tsx, src/routes/settings/components/__tests__/DebugModal.spec.tsx, src/services/AsyncStorage.ts, src/services/axios.ts
=> LUN-292: Add switch for cms

release-notes/unreleased/LUN-341-make-articles-lowercase.yml, src/components/__tests__/VocabularyList.spec.tsx, src/constants/data.ts, src/hooks/__tests__/useLoadDocuments.spec.ts, src/routes/__tests__/VocabularyListScreen.spec.tsx, src/routes/choice-exercises/__tests__/ArticleChoiceExerciseScreen.spec.tsx, src/routes/write-exercise/__tests__/WriteExerciseScreen.spec.tsx, src/routes/write-exercise/components/InteractionSection.tsx, src/routes/write-exercise/components/__tests__/InteractionSection.spec.tsx
=> LUN-341: Uncapitalized articles and adjusted tests

ios/Podfile.lock
Since we had some major library updates i had to:
- delete pods (ios/pods) folder & podfile.lock
- `pod install --repo-update`
But everything should work now with new `podfile.lock`
=> LUN-350: Upgrade pods for ios

src/constants/labels.json, src/routes/exercises/ExercisesScreen.tsx
=> LUN-385: Adjust button wording of locking modal

src/constants/labels.json, src/routes/home/components/DisciplineCard.tsx, src/routes/home/components/__tests__/DisciplineCard.spec.tsx, src/routes/manage-selections/__tests__/ManageSelectionsScreen.spec.tsx, src/routes/manage-selections/components/SelectionItem.tsx
=> LUN-374: Add confirmation modal for delete selection

release-notes/unreleased/LUN-388-fix-locking-lane-misalignment.yml, src/routes/exercises/components/LockingLane.tsx
=> LUN-388: Fix locking lane misalignment

release-notes/unreleased/LUN-373-remove-shadow-from-star-icon.yml, src/components/FavoriteButton.tsx
=> LUN-373: Remove shadow from Star icon

release-notes/unreleased/LUN-391-repeat-show-solution.yml, src/routes/write-exercise/WriteExerciseScreen.tsx, src/routes/write-exercise/__tests__/WriteExerciseScreen.spec.tsx
=> LUN-391: Repeat words after solution shown

assets/images/index.ts, assets/images/no-internet-connection.svg, release-notes/unreleased/LUN-209-no-internet-connection.yml, src/components/ErrorMessage.tsx, src/components/RoundedBackground.tsx, src/components/__tests__/ErrorMessage.spec.tsx, src/constants/labels.json, src/constants/theme/colors.ts, src/routes/exercise-finished/ExerciseFinishedScreen.tsx, src/routes/home/components/DisciplineCard.tsx
=> LUN-209: No internet connection

src/components/VocabularyList.tsx, src/routes/ImprintScreen.tsx, src/routes/add-custom-discipline/components/NotAuthorisedView.tsx, src/routes/choice-exercises/components/SingleChoiceExercise.tsx, src/routes/settings/SettingsScreen.tsx
=> LUN-304: Remove background color of containers

src/components/ExerciseHeader.tsx, src/components/FeedbackModal.tsx, src/components/Modal.tsx, src/components/ModalSkeleton.tsx, src/components/__tests__/Modal.spec.tsx, src/routes/add-custom-discipline/components/QRCodeReaderOverlay.tsx, src/routes/exercises/ExercisesScreen.tsx, src/routes/manage-selections/components/SelectionItem.tsx
=> LUN-371: Rename CustomModal

release-notes/unreleased/LUN-378-add-heading-profession-selection.yml, src/components/text/Heading.tsx, src/routes/scope-selection/ScopeSelectionScreen.tsx
=> LUN-378: Add heading to profession selection

.circleci/config.yml, .circleci/src/jobs/deliver_android.yml, .circleci/src/jobs/deliver_ios.yml
=> LUN-xx: Fix sentry upload

release-notes/unreleased/LUN-412-adjust-wording.yml, src/constants/labels.json, src/routes/exercises/ExercisesScreen.tsx, src/routes/vocabulary-detail/VocabularyDetailScreen.tsx
=> LUN-412: Adjust wording

release-notes/unreleased/LUN-404-fix-favorites-detail-screen.yml, src/components/ExerciseHeader.tsx, src/navigation/NavigationTypes.ts, src/routes/FavoritesScreen.tsx, src/routes/vocabulary-detail/VocabularyDetailScreen.tsx
=> LUN-404: fix buttons on favorite detail screen

src/components/ExerciseHeader.tsx, src/constants/theme/index.ts, src/constants/theme/spacings.ts, src/navigation/BottomTabNavigator.tsx, src/navigation/screenOptions.tsx
=> LUN-426: Inline style spacings

src/components/AudioRecorder.tsx, src/hooks/useGrantPermissions.ts, src/routes/process-user-vocabulary/components/AudioRecordOverlay.tsx
=> LUN-399: Fix flickering

src/components/AudioPlayer.tsx, src/components/AudioRecorder.tsx, src/components/VocabularyItemImageSection.tsx, src/components/VocabularyListItem.tsx, src/components/__tests__/AudioPlayer.spec.tsx, src/routes/process-user-vocabulary/UserVocabularyProcessScreen.tsx
=> LUN-399: Proposal

README.md, docs/debugging.md
Just a little step I found necessary in setting up the app.
=> LUN-xxx: Update the README

src/components/AudioRecorder.tsx, src/routes/process-user-vocabulary/components/AudioRecordOverlay.tsx
=> Lun-399: Fix fast recording stop

android/app/src/main/AndroidManifest.xml
=> LUN-467: Playstore issues

.circleci/config.yml, .circleci/src/commands/notify.yml
I strongly believe that it is extremely important to always use the appropriate emojis on all occasions.
=> LUN-xxx: Use Lunes emoji for Mattermost notifications

release-notes/unreleased/LUN-401-finalize-own-vocabulary.yml, src/constants/endpoints.ts, src/routes/UserVocabularyOverviewScreen.tsx, src/routes/user-vocabulary-discipline-selection-screen/__tests__/UserVocabularyDisciplineSelectionScreen.spec.tsx, src/routes/user-vocabulary-discipline-selection-screen/splitVocabularyToDiscipline.ts, src/routes/user-vocabulary-list/UserVocabularyListScreen.tsx, src/routes/user-vocabulary-list/components/ListEmptyContent.tsx, tools/git-version.ts
=> LUN-401: Cleanup for own vocabulary

CODEOWNERS
=> Add Leandra to Codeowners

tools/package.json, tools/yarn.lock
=> LUN-xx: Add lodash

.circleci/config.yml, .circleci/src/jobs/notify_android.yml, .circleci/src/jobs/notify_ios.yml
=> LUN-xx: Fix release notes CICD

src/components/ExerciseHeader.tsx
=> LUN-483: Fixed header button back to word list on word list screen

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/app/lunes/MainApplication.java, android/app/src/main/java/app/lunes/newarchitecture/MainApplicationReactNativeHost.java, android/app/src/main/java/app/lunes/newarchitecture/components/MainComponentsRegistry.java, android/app/src/main/java/app/lunes/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
=> LUN-506: Replace occurrences of com.lunes with app.lunes

release-notes/unreleased/LUN-513-change-wording-sponsor.yml, src/constants/labels.json
Also see https://chat.tuerantuer.org/digitalfabrik/pl/9d39n7qap7dnmx1um8qehfsgec
=> LUN-513: Change wording sponsor

src/constants/labels.json
=> LUN-508: Change welcome text

src/services/__tests__/helpers.spec.ts, src/services/helpers.ts, src/testing/VocabularyItemBuilder.ts
=> LUN-480: Fix filtering with special characters

.circleci/config.yml, .circleci/src/jobs/build_android.yml, .circleci/src/jobs/bump_version.yml, .circleci/src/jobs/check.yml, .circleci/src/jobs/deliver_android.yml, .circleci/src/jobs/deliver_browser_stack.yml, .circleci/src/jobs/move_release_notes.yml, .circleci/src/jobs/notify_android.yml, .circleci/src/jobs/notify_ios.yml, .circleci/src/jobs/promote_android.yml
=> LUN-529: update node to 18

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/task.md, .github/ISSUE_TEMPLATE/technical-task.md, .github/ISSUE_TEMPLATE/user-story.md, .github/PULL_REQUEST_TEMPLATE.md
Will probably wait till https://github.com/digitalfabrik/integreat-app/pull/2302 is finished :)
=> Add issue and PR template

src/routes/process-user-vocabulary/UserVocabularyProcessScreen.tsx, src/services/helpers.ts
Just updating one JIRA ticket number and removing one that is already done.
Fixes: #985 
---
=> 985 Replace JIRA ticket numbers with Github issue numbers

src/navigation/BottomTabNavigator.tsx
With this solution the footer only updates, when an icon is pressed. I think this is enough for now, as we otherwise would need to implement some sort of listener, which I think is out of scope.
Fixes: #902
---
=> 902: Repetition Exercise footer badge

ios/Gemfile.lock, release-notes/unreleased/LUN-528-delete-deleted-photos.yml, src/routes/process-user-vocabulary/UserVocabularyProcessScreen.tsx, src/routes/process-user-vocabulary/__tests__/UserVocabularyProcessScreen.spec.tsx, src/services/AsyncStorage.ts, src/services/__tests__/AsyncStorage.spec.ts
This pull request belongs to the issue https://issues.tuerantuer.org/browse/LUN-528 on our bug tracker.
=> LUN-528: Delete deleted photos on saving

src/navigation/BottomTabNavigator.tsx, src/navigation/NavigationTypes.ts, src/routes/repetition/RepetitionScreen.tsx, src/routes/repetition/__tests__/RepetitionScreen.spec.tsx, src/routes/repetition/components/RepetitionProgressChart.tsx, src/routes/settings/components/DebugModal.tsx, src/routes/write-exercise/WriteExerciseScreen.tsx, src/routes/write-exercise/services/AbstractWriteExerciseService.ts, src/routes/write-exercise/services/RepetitionWriteExerciseService.ts, src/routes/write-exercise/services/StandardWriteExerciseService.ts, src/routes/write-exercise/services/__tests__/RepetitionWriteExerciseService.spec.ts, src/routes/write-exercise/services/__tests__/StandardWriteExerciseService.spec.tsx, src/services/RepetitionService.ts, src/services/__tests__/RepetitionService.spec.ts
Could break any existing logic of the writing exercise. Should be tested.
Fixes: #905
=> 905: Adjust write exercise for repetition exercise

README.md
Found a typo, couldn't leave it alone. And updated Steffi's email address while I was at it.
=> Fixing a typo and the old email address

.circleci/config.yml, .circleci/src/commands/notify.yml, CODEOWNERS, README.md
Handing over to the platform team
=> Handing over to the platform team

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/task.md, .github/PULL_REQUEST_TEMPLATE.md
Just a small annoyance: the help texts were not added as comments, which required removing them manually in the issue
=> Fix task issue template

release-notes/unreleased/1088-move-words-to-long-term-memory-exercise-after-each-level.yml, release-notes/unreleased/1098-detect-silence-mode.yml
The update was only in beta and will be yanked to provide an additional bugfix in the full-release
- Copy the release notes into unreleased, so that the next update will show them too
Fixes: #
---
=> Copy release notes from 2025.7.0 back to unreleased

src/components/VocabularyList.tsx, src/components/__tests__/VocabularyList.spec.tsx, src/constants/labels.json, src/routes/__tests__/VocabularyListScreen.spec.tsx, src/routes/dictionary/DictionaryScreen.tsx, src/routes/dictionary/__tests__/DictionaryScreen.spec.tsx, src/routes/exercise-finished/ExerciseFinishedScreen.tsx, src/routes/exercise-finished/__tests__/ExerciseFinishedScreen.spec.tsx, src/routes/favorites/FavoritesScreen.tsx, src/routes/repetition/RepetitionWordListScreen.tsx, src/routes/repetition/__tests__/RepetitionWordListScreen.spec.tsx, src/routes/repetition/components/RepetitionProgressChart.tsx, src/routes/special-exercises/__tests__/SpecialExercisesScreen.spec.tsx, src/routes/user-vocabulary-discipline-selection/__tests__/UserVocabularyDisciplineSelectionScreen.spec.tsx, src/routes/user-vocabulary-list/UserVocabularyListScreen.tsx, src/routes/user-vocabulary-list/__tests__/UserVocabularyListScreen.spec.tsx, src/services/helpers.ts
This should make the code a bit more compact and easier to read
- use `pluralize` and `wordDescription` where possible
- Add more plurals to labels
- Should have no side effects
Fixes: #1158 
---
=> Use `pluralize` and `wordDescription`
